### ISSUE TITLE
can we make request() public ?

### ISSUE THREAD

**Issue by acmartinsalmeida** [Tiloweb/tiloweb-matpe#2]
$products = $this->get("matpe")->request('GET', 'products'); would be ok but it's private.

Can we put this public ? or can i help to add the other function of facturation.pro ?

**Comment by nicosomb** [comment]
Hello @smartinsalmeida!

You need to create a `getProducts()` method in `Tiloweb\MaTPEBundle\Service\MaTPEService`. 

For example, something like that (I didn't try this code): 
```
    public function getProducts()
    {
        return $this->request('GET', '/products');
    }
```

**Comment by acmartinsalmeida** [comment]
Thanks @nicosomb for your reply

I use this bundle in Symfony !

Yeah that's what i think to do...but it's a "vendor" bundle and i think fork isn't a good solution for this purpose !

**Comment by nicosomb** [comment]
OK. Pull request is welcome I think ;-)

**Comment by acmartinsalmeida** [comment]
I think too but don't know how do that :( I fork, change and send PR ?

**Comment by nicosomb** [comment]
Exactly.

**Comment by Tilotiti** [comment]
Please, help yourself :)
The purpose of this Bundle is to offer an abstraction class. So we want to avoid direct API call.

PS : on serait pas tous français par hasard ?

**Comment by nicosomb** [comment]
Exactly 😁

**Comment by acmartinsalmeida** [comment]
Désolé pour le retard. Merci pour le PR (nous sommes tous français en effet)

Sorry to be late. thanks for the PR (we are all french)

**Comment by acmartinsalmeida** [comment]
ça vient moi ou j'ai fait mon PR au mauvais endroit ?

**Comment by Tilotiti** [comment]
Heu non, tout semble ok, pourquoi ?

**Comment by acmartinsalmeida** [comment]
Oui c'est ok mais c'est @nicosomb qui l'a envoyé aussi j'imagine que j'ai probablement pas fait ce qu'il fallait. le mien est là https://github.com/smartinsalmeida/tiloweb-matpe/pull/1

**Comment by nicosomb** [comment]
When you want to open a new pull request, you need to open it from your repository to the main repository (the Tiloweb one). You can have a look here https://help.github.com/articles/about-pull-requests/

**Comment by acmartinsalmeida** [comment]
Merci @nicosomb je ferais mieux la prochaine fois, j'ai d'autres méthodes à ajouter :)
